#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Requirements Parser documentation build configuration file, created by
# sphinx-quickstart on Fri Aug 16 07:44:12 2013.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# -- Project information -----------------------------------------------------
import pkg_resources

project = "Requirements Parser"
copyright = "2015 - David Fischer, 2021 - Paul Horton"
author = "David Fischer, Paul Horton"

# The full version, including alpha/beta/rc tags
release = pkg_resources.get_distribution("requirements-parser").version


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    # "sphinx.ext.napoleon",
    # "sphinx.ext.intersphinx",
    # "sphinx.ext.autosectionlabel",
    # "sphinx_copybutton",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = "alabaster"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

intersphinx_mapping = {"python": ("http://docs.python.org/3", None)}